version: '3.8'
services:
  pose:
    build:
      context: ./posedetection
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1,2,3,4

  gpt:
    build:
      context: ./gptnhomepage
      dockerfile: Dockerfile
    depends_on:
      - pose
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=5,6,7,8,9